"""initial migration

Revision ID: 48bbdd4ac281
Revises: 3652a4873b42
Create Date: 2026-02-07 10:40:12.989783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bbdd4ac281'
down_revision = '3652a4873b42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###